Repository TeamNAJ/transcendence, pull requests merged in 2023-08, with the labels that each got.

#28 MERGE ADD MUI BASE && PERSISTING REDUX:
  .gitignore
  front/Makefile
  front/app/package.json
  front/app/src/App.tsx
  front/app/src/Redux/hooks/redux-hooks.ts
  front/app/src/Redux/models/redux-models.ts
  front/app/src/Redux/service/server-service.ts
  front/app/src/Redux/store/Api.ts
  front/app/src/Redux/store/controller-slice.ts
  front/app/src/Redux/store/controllerAction.ts
  front/app/src/Redux/store/index.ts
  front/app/src/Redux/store/server-slice.ts
  front/app/src/Redux/store/serverAction.ts
  front/app/src/Theme/BehaviourLinkOption.ts
  front/app/src/Theme/CustomDarkTheme.ts
  front/app/src/Theme/CustomLightTheme.ts
  front/app/src/Theme/LinkBehaviour.tsx
  front/app/src/Theme/index.ts
  front/app/src/Views/BaseViewFromVitejs/components/DocInfoBase.tsx
  front/app/src/main.tsx
Labels: feature

#19 MERGE BASE BACKEND:
  backend/Dockerfile
  backend/Makefile
  backend/app/.eslintrc.js
  backend/app/.gitignore
  backend/app/.prettierrc
  backend/app/nest-cli.json
  backend/app/package.json
  backend/app/processes.json
  backend/app/src/app.controller.spec.ts
  backend/app/src/app.controller.ts
  backend/app/src/app.module.ts
  backend/app/src/app.service.ts
  backend/app/src/main.ts
  backend/app/test/app.e2e-spec.ts
  backend/app/test/jest-e2e.json
  backend/app/tsconfig.build.json
  backend/app/tsconfig.json
Labels: documentation, feature

#36 MERGE INSTALLING NODEJS WITH VOLTA && FIX SUDO CLEAN:
  backend/Dockerfile
  backend/Makefile
  front/Dockerfile
  front/Makefile
Labels: fix, update

#37 MERGE FIX DEPENDENCY DEPRECATED:
  front/app/package.json
  front/app/src/Router/VisitorRouter.tsx
Labels: fix

#41 MERGE POSTGRES CONTAINER:
  .env.sample
  database/.env.sample
  database/Dockerfile
  database/Makefile
  database/database.sql
Labels: feature

#46 UPDATE MAKEFILE (FRONT):
  front/Makefile
Labels: update

#45 FIX NODE CRITICAL VULNERABILITY:
  backend/Dockerfile
  front/Dockerfile
Labels: fix
